lithuanian_cities:
- Vilnius
- Kaunas
- Klaipėda
- Šiauliai
- Panevėžys
- Alytus
- Marijampolė
- Mažeikiai
- Jonava
- Utena
- Kėdainiai
- Telšiai
- Tauragė
- Ukmergė
- Visaginas
- Plungė
- Kretinga
- Radviliškis
- Palanga
- Druskininkai
- Gargždai
- Rokiškis
- Biržai
- Jurbarkas
- Elektrėnai
- Kuršėnai
- Garliava
- Vilkaviškis
- Anykščiai
- Lentvaris
- Prienai
- Joniškis
- Šilutė
- Šilalė
- Raseiniai
- Kelmė
- Varėna
- Kaišiadorys
- Pasvalys
- Kupiškis
- Zarasai
- Širvintos
- Molėtai
- Ignalina
- Švenčionys
- Trakai
- Šakiai
- Kazlų Rūda
- Vilkija
- Grigiškės
- Nemenčinė
- Vilniaus
- Kauno
- Klaipėdos
- Šiaulių
- Panevėžio
- Alytaus
- Marijampolės
- Tauragės
- Telšių
- Utenos
- rajonas
- raj.
- sav.
- savivaldybė
- apskritis
- aps.
- Antakalnis
- Žirmūnai
- Lazdynai
- Fabijoniškės
- Pilaitė
- Justiniškės
- Viršuliškės
- Šeškinė
- Naujamiestis
- Senamiestis
- Užupis
- Žvėrynas
metadata:
  description: Lithuanian cities and locations for PII detection
  last_updated: '2025-05-27T15:18:03.101516'
  version: 1.0.0
