metadata:
  description: PII detection patterns for AnonymPDF
  last_updated: '2025-05-27T15:18:03.079944'
  version: 1.0.0
pii_patterns:
  blood_group: (?<!\w)(?:A|B|AB|O)[\+\-](?!\w)
  credit_cards: \b\d{4}[- ]?\d{4}[- ]?\d{4}[- ]?\d{4}\b
  credit_card_enhanced: \b(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|3[47][0-9]{13}|6(?:011|5[0-9]{2})[0-9]{12})\b
  date_yyyy_mm_dd: \b\d{4}-\d{2}-\d{2}\b
  date_yyyy_mm_dd_dots: \d{4}\.\d{2}\.\d{2}
  eleven_digit_numeric: \b\d{11}\b
  emails: \b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b
  health_insurance_number: \b\d{6,12}\b
  iban_eu: \b[A-Z]{2}\d{2}[A-Z0-9]{1,30}\b
  legal_entity_code: \b\d{8,9}\b
  lithuanian_address_generic: \b[A-ZĄČĘĖĮŠŲŪŽ][a-ząčęėįšųūž]{2,}\s+(?:g|pr|al)\.\s*\d+[A-Za-z]?(?:-\d+)?(?:,\s*LT-\d{5})?(?:,\s*[A-ZĄČĘĖĮŠŲŪŽ][a-ząčęėįšųūž\s]+)?
  lithuanian_address_prefixed: Adresas:\s*[^,\n\r]+(?:g|pr|al)\.\s*[^,\n\r]+(?:,\s*LT-\d{5})?(?:,\s*[^\n\r]+)?
  lithuanian_business_cert: \bAF\d{6}-\d\b
  lithuanian_business_cert_alt: \b\d{9}\b
  lithuanian_car_plate: \b[A-Z]{3}[-\s]?\d{3}\b
  lithuanian_driver_license: \b[A-Z]{1,2}\d{6,7}[A-Z]?\b
  lithuanian_iban: \bLT\d{18}\b
  LITHUANIAN_PHONE_NUMBER: '(?:\+370|8)[\s-]?\d{3}[\s-]?\d{2}[\s-]?\d{3}|\+370[\s-]?\d{3}[\s-]?\d{5}'
  lithuanian_mobile_prefixed: 'Tel\.\s*(?:nr\.\s*:?\s*)?((?:\+370|8)[\s-]?\d{3}[\s-]?\d{2}[\s-]?\d{3}|\+370[\s-]?\d{3}[\s-]?\d{5})\b'
  lithuanian_passport: \b[A-Z]{2}\d{7}\b
  lithuanian_personal_code: \b[3-6]\d{10}\b
  lithuanian_phone_compact: \+370\d{8}\b
  lithuanian_phone_generic: '((?:\+370|8)[\s-]?\d{3}[\s-]?\d{2}[\s-]?\d{3}|\+370[\s-]?\d{3}[\s-]?\d{5,})\b'
  lithuanian_postal_code: \bLT-\d{5}\b
  lithuanian_vat_code: \bLT\d{9,12}\b
  lithuanian_vat_code_labeled: PVM\s+kodas:?\s*LT\d{9,12}
  lithuanian_city_simple: \b(Vilnius|Kaunas|Klaipėda|Šiauliai|Panevėžys)(?:o|je|ui|aus)?\b
  medical_record_number: \b\d{6,10}\b
  phone: \b(?:\+\d{1,3}[-.\s]?)?\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}\b
  phone_international: \+\d{1,3}\s+\d{3}\s+\d{5,6}\b
  ssns: \b\d{3}[-]?\d{2}[-]?\d{4}\b
  swift_bic: \b[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}(?:[A-Z0-9]{3})?\b
  # Morning Session 5 Improvements - Enhanced car plate detection
  lithuanian_car_plate_contextual: (?i)[Vv]alst\.?\s*[Nn]r\.?\s*[:\-]?\s*([A-Z]{3}[-\s]?\d{3})\b
  # Morning Session 5 Improvements - Simple Lithuanian Name
  lithuanian_name_simple: \b([A-ZĄČĘĖĮŠŲŪŽ][a-ząčęėįšųūž]+\s[A-ZĄČĘĖĮŠŲŪŽ][a-ząčęėįšųūž]+(?:ienė|aitė|ytė|utė|ūtė|as|is|ys|us|ius|ė|a)?)\b
  # Morning Session 5 Improvements - Enhanced Lithuanian name detection (ALL CAPS)
  lithuanian_name_all_caps: \b([A-ZČĘĖĮŠŲŪŽ]{2,}(?:IENĖ|AITĖ|YTĖ|UTĖ|ŪTĖ|AS|IS|YS|US|IUS|Ė|A))\s+([A-ZČĘĖĮŠŲŪŽ]{2,}(?:IENĖ|AITĖ|YTĖ|UTĖ|ŪTĖ|AS|IS|YS|US|IUS|Ė|A))|\b([A-ZČĘĖĮŠŲŪŽ]{2,})\s+([A-ZČĘĖĮŠŲŪŽ]{2,}(?:IENĖ|AITĖ|YTĖ|UTĖ|ŪTĖ|AS|IS|YS|US|IUS|Ė|A))\b
  # Morning Session 5 Improvements - Enhanced Lithuanian name after context keywords  
  lithuanian_name_contextual: (?:Draudėjas|Vardas|Pavardė|Sutartį\s+sudarė)[\s:–-]*([A-ZĄČĘĖĮŠŲŪŽ][a-ząčęėįšųūž]+(?:\s+[A-ZĄČĘĖĮŠŲŪŽ][a-ząčęėįšųūž]+)*(?:ienė|aitė|ytė|utė|ūtė|as|is|ys|us|ius|ė|a))\b
  # Morning Session 5 Improvements - Enhanced Lithuanian name contextual ALL CAPS
  lithuanian_name_contextual_caps: (?:Draudėjas|DRAUDĖJAS|Vardas|VARDAS)[\s:–-]*([A-ZČĘĖĮŠŲŪŽ]{3,}\s+[A-ZČĘĖĮŠŲŪŽ]{3,})\b
  # Morning Session 5 Improvements - Enhanced flexible address patterns
  lithuanian_address_flexible: \b([A-ZĄČĘĖĮŠŲŪŽ][a-ząčęėįšųūž]{3,}(?:io|ės)?)\s*(?:g\.|gatvė|pr\.|prospektas|al\.|alėja)?(?:\s*\d+(?:[A-Za-z]?(?:-\d+)?)?)?
  # Morning Session 5 Improvements - Personal code with explicit context
  lithuanian_personal_code_contextual: (?:asmens\s+kodas|asmens/įmonės\s+kodas|A\.K\.)[\s:–-]*(\d{11})\b
  # Morning Session 5 Improvements - Enhanced car plate with various formats
  lithuanian_car_plate_enhanced: (?i)(?:valst\.?\s*nr\.?|automobilio\s+nr\.?|numeris)[\s:–-]*([A-Z]{3}[-\s]?\d{3})\b
