language_detection:
  enabled: true
  sample_size: 1000
logging:
  backup_count: 5
  level: INFO
  max_file_size_mb: 10
patterns:
  case_sensitive: false
  validate_on_load: true
  word_boundaries: true
processing:
  max_file_size_mb: 50
  temp_cleanup: true
  timeout_seconds: 300
version: 1.0.0

# Morning Session 5 Improvements - Anti-overredaction settings
anti_overredaction:
  # Technical terms that should never be redacted
  technical_terms_whitelist:
    - "kW"
    - "Nm" 
    - "g/km"
    - "l/100 km"
    - "mm"
    - "kg"
    - "cm³"
    - "CO2 emisijos"
    - "Maks. variklio galia"
    - "Degalų sąnaudos"
    - "SVORIS"
    - "VAŽ."
    - "Pareigos"
    - "Kaina"
    - "Netto atlyginimas"
    - "Kitos pajamos"
    - "Gyvenamoji vieta"
    
  # Field labels that are always PII and should be redacted
  pii_field_labels:
    - "Vardas"
    - "Pavardė"
    - "Vardas, pavardė"
    - "Asmens kodas"
    - "Paso Nr"
    - "Adresas"
    - "Telefono numeris"
    - "El. paštas"
    - "Banko sąskaita"
    - "Asmens socialinio draudimo pažymėjimo Nr"
    - "Draudėjas"
    - "Valst. Nr"
    - "VIN"
    
  # Section headers that indicate technical data (suppress redaction)
  technical_sections:
    - "SVORIS"
    - "VAŽ."
    - "Degalų sąnaudos"
    - "Techniniai duomenys"
    - "Automobilio duomenys"
    - "Variklio duomenys"

# Morning Session 8 - Adaptive Learning Integration
adaptive_learning:
  enabled: true
  databases:
    patterns_db: "data/adaptive/patterns.db"
    ab_tests_db: "data/adaptive/ab_tests.db"
    analytics_db: "data/adaptive/analytics.db"
  thresholds:
    min_confidence_to_validate: 0.95
    min_samples_for_learning: 10
    ab_test_confidence_level: 0.95
  ab_tests:
    ab_93940a98:            # būtent toks testo ID, kokį generuoja jūsų sistema
      control_mean: 0.85
      variant_mean: 0.90
      sample_size: 1000
  monitoring:
    log_learning_events: true
    track_pattern_usage: true
    alert_on_anomalies: true

# Performance settings for caching, threading, etc.
performance:
  cache_size: 1000
  cache_ttl_seconds: 3600
  max_workers: 4
  parallel_processing:
    max_workers: 4
    chunk_size: 100
  batch_engine:
    max_batch_size: 100
    batch_timeout_seconds: 10

# Feedback System Configuration
feedback_system:
  storage_path: "data/user_feedback.db"
  min_feedback_for_retraining: 50
  auto_retrain_enabled: true

